name: Deploy to EC2

on:
  push:
    branches:
      - main # Replace with your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }} # Example of using a secret as an environment variable

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn

      - name: Build application
        run: yarn build

      - name: Connect to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }} # Public IP or DNS of your EC2 instance
          username: ${{ secrets.USERNAME }} # Username on your EC2 instance (e.g., 'ec2-user')
          key: ${{ secrets.SSHKEY }} # Private key for SSH access (stored as a GitHub secret)
          source: ./ # Source directory for files to be transferred
          target: /home/ubuntu/deployments # Target directory on the EC2 instance

      - name: Restart application on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd /home/ubuntu/deployments 
            pm2 restart all # Restart all PM2 processes
